### Indexing and Slicing

In [1]:
import numpy as np

In [3]:
array = np.array([3,6,7,8,9,2])
array

array([3, 6, 7, 8, 9, 2])

In [5]:
array[0]

3

In [7]:
array[1]

6

In [10]:
array[-1]

2

In [12]:
array = np.array([3,6,7,8,9,2])
array[-2]

9

In [14]:
array = np.array([[3,6,7],[8,9,2]])
array

array([[3, 6, 7],
       [8, 9, 2]])

In [16]:
array = np.array([[3,6,7],[8,9,2]])
array[1][0]

8

In [18]:
array = np.array([[3,6,7],[8,9,2]])
array[1][-1]

2

In [19]:
array = np.array([[3,6,7],[8,9,2]])
array[1,-1]

2

In [22]:
x = [[3,6,7],[8,9,2]]
x[1][-1]

2

In [24]:
x = [[3,6,7],[8,9,2]]
x[1,-1]

TypeError: list indices must be integers or slices, not tuple

In [26]:
array = np.array([3,6,7,8,9,2])
array[1:4]

array([6, 7, 8])

In [29]:
array = np.array([3,6,7,8,9,2])
array[-5:-2]# -5,-4,-3

array([6, 7, 8])

In [30]:
array = np.array([3,6,7,8,9,2])
array[::1]

array([3, 6, 7, 8, 9, 2])

In [32]:
array = np.array([3,6,7,8,9,2])
array[::-1]

array([2, 9, 8, 7, 6, 3])

In [34]:
array = np.array([3,6,7,8,9,2])
array[4:2:-1] # 

array([9, 8])

In [37]:
array = np.array([[3,6,7,8],[9,2,1,7],[10,20,30,40]])
array

array([[ 3,  6,  7,  8],
       [ 9,  2,  1,  7],
       [10, 20, 30, 40]])

In [38]:
array[2,1]

20

In [41]:
array = np.array([[3,6,7,8],[9,2,1,7],[10,20,30,40]])
print(array)
array[:,:]

[[ 3  6  7  8]
 [ 9  2  1  7]
 [10 20 30 40]]


array([[ 3,  6,  7,  8],
       [ 9,  2,  1,  7],
       [10, 20, 30, 40]])

In [47]:
array = np.array([[3,6,7,8],[9,2,1,7],[10,20,30,40]])
print(array)
array[1,2]

[[ 3  6  7  8]
 [ 9  2  1  7]
 [10 20 30 40]]


1

In [46]:
array = np.array([[3,6,7,8],[9,2,1,7],[10,20,30,40]])
array[1,1]

2

In [49]:
array = np.array([[3,6,7,8],[9,2,1,7],[10,20,30,40]])
array[1,:]

array([9, 2, 1, 7])

In [50]:
array = np.array([[3,6,7,8],[9,2,1,7],[10,20,30,40]])
array

array([[ 3,  6,  7,  8],
       [ 9,  2,  1,  7],
       [10, 20, 30, 40]])

In [52]:
array = np.array([[3,6,7,8],[9,2,1,7],[10,20,30,40]])
array[:,2]

array([ 7,  1, 30])

In [53]:
array = np.array([[3,6,7,8],[9,2,1,7],[10,20,30,40]])
array[2, 1:3]

array([20, 30])

In [54]:
array = np.array([[3,6,7,8],[9,2,1,7],[10,20,30,40]])
array

array([[ 3,  6,  7,  8],
       [ 9,  2,  1,  7],
       [10, 20, 30, 40]])

In [55]:
array[0:2,1:3]

array([[6, 7],
       [2, 1]])

In [57]:
array[-3:-1,1:3]

array([[6, 7],
       [2, 1]])

In [61]:
array3 = np.array([[[3,6,7,8],[9,2,1,7]],[[10,20,30,40],[30,60,70,80]]])
array3

array([[[ 3,  6,  7,  8],
        [ 9,  2,  1,  7]],

       [[10, 20, 30, 40],
        [30, 60, 70, 80]]])

In [63]:
array3.shape # 2,2,4

(2, 2, 4)

In [65]:
array3[1]

array([[10, 20, 30, 40],
       [30, 60, 70, 80]])

In [67]:
array3[1,0,2]

30

In [69]:
array3 = np.array([[[3,6,7,8],[9,2,1,7]],[[10,20,30,40],[30,60,70,80]]])
array3

array([[[ 3,  6,  7,  8],
        [ 9,  2,  1,  7]],

       [[10, 20, 30, 40],
        [30, 60, 70, 80]]])

In [70]:
array3[1,0,1:]

array([20, 30, 40])

In [72]:
array3[:,1,1:-1]

array([[ 2,  1],
       [60, 70]])

In [74]:
array3[:,:,1:-1]

array([[[ 6,  7],
        [ 2,  1]],

       [[20, 30],
        [60, 70]]])

### Access items using for Loop

In [75]:
array1 = np.array([3,6,7,8,9,2])
array1

array([3, 6, 7, 8, 9, 2])

In [77]:
for i in array1:
    print(i)

3
6
7
8
9
2


In [79]:
array2 = np.array([[3,6,7],[8,9,2]])
for i in array2:
    print(i)

[3 6 7]
[8 9 2]


In [81]:
array2 = np.array([[3,6,7],[8,9,2]])
for i in array2:
    for j in i:
        print(j)

3
6
7
8
9
2


In [86]:
array3 = np.array([[[3,6,7],[8,9,2]],[[31,61,71],[81,19,12]]])
for i in array3:
    print(i)
    print("********")

[[3 6 7]
 [8 9 2]]
********
[[31 61 71]
 [81 19 12]]
********


In [88]:
array3 = np.array([[[3,6,7],[8,9,2]],[[31,61,71],[81,19,12]]])
for i in array3:
    for j in i:
        for k in j:
            print(k)

3
6
7
8
9
2
31
61
71
81
19
12


In [91]:
array3 = np.array([[[3,6,7],[8,9,2]],[[31,61,71],[81,19,12]]])
for i in array3.reshape(array3.size):
    print(i)

3
6
7
8
9
2
31
61
71
81
19
12


### 1. np.nditer()

In [93]:
array1 = np.array([3,6,7,8,9,2])
for i in np.nditer(array1):
    print(i)

3
6
7
8
9
2


In [95]:
array2 = np.array([[3,6,7],[8,9,2]])
for i in np.nditer(array2):
    print(i)

3
6
7
8
9
2


In [112]:
array3 = np.array([[[3,6,7],[8,9,2]],[[31,61,71],[81,19,12]]])
for i in np.nditer(array3):
    print(i)

3
6
7
8
9
2
31
61
71
81
19
12


### 2. np.ndenumerate()

In [101]:
array1 = np.array([3,6,7,8,9,2])
for index,val in np.ndenumerate(array1):
    print(index, val)

(0,) 3
(1,) 6
(2,) 7
(3,) 8
(4,) 9
(5,) 2


In [103]:
array2 = np.array([[3,6,7],[8,9,2]])
array2

array([[3, 6, 7],
       [8, 9, 2]])

In [104]:
array2[0,0]

3

In [107]:
array2 = np.array([[3,6,7],[8,9,2]])
for index,val in np.ndenumerate(array2):
    print(index,">>",val)

(0, 0) >> 3
(0, 1) >> 6
(0, 2) >> 7
(1, 0) >> 8
(1, 1) >> 9
(1, 2) >> 2


In [109]:
array3 = np.array([[[3,6,7],[8,9,2]],[[31,61,71],[81,19,12]]])
for index,val in np.ndenumerate(array3):
    print(index,">>",val)

(0, 0, 0) >> 3
(0, 0, 1) >> 6
(0, 0, 2) >> 7
(0, 1, 0) >> 8
(0, 1, 1) >> 9
(0, 1, 2) >> 2
(1, 0, 0) >> 31
(1, 0, 1) >> 61
(1, 0, 2) >> 71
(1, 1, 0) >> 81
(1, 1, 1) >> 19
(1, 1, 2) >> 12


In [111]:
array3[1, 0, 2]

71